---
# Install PostgreSQL

     - name: POSTGRESQL | Check Postgres has been installed
       stat: path=/etc/postgresql
       register: postgres_exists
 
     - name: POSTGRESQL | Install postgres
       become: yes
       apt:
         pkg: "{{ item }}"
         state: latest
       with_items:
         - postgresql
         - postgresql-contrib
         - libpq-dev
         - python-psycopg2
       register: postgresinstalled
              
     - name: POSTGRES | Add postgres config
       when: postgresinstalled|success
       become: true
       template: src=pg_hba.conf dest=/etc/postgresql/9.5/main/
       notify: restart postgresql

     - name: POSTGRES | Add databases
       when: postgresinstalled|success
       become: yes
       become_user: postgres
       postgresql_db:
          name: "{{db_name}}"

     - name: Python | Installing pip and dev
       become: true
       apt:
         pkg: "{{ item }}"
         state: latest
       with_items:
         - python-pip
         - python-dev

     - name: pip | Updating pip
       become_method: sudo
       pip:
         name: pip
         extra_args: --upgrade

     - name: DATABASE | Copying Initialization files
       become: true
       copy: src={{db_file}} dest="{{install_directory}}" 

     - name: DATABASE | Install Dependencies
       become: true
       pip:
         requirements: "{{db_requirements_file}}"

     - name: DATABASE | Initialize
       become: true
       command: "python {{install_directory}}database/main.py"         

