---
# Install PostgreSQL

     - name: POSTGRESQL | Check Postgres has been installed
       stat: path=/etc/postgresql
       register: postgres_exists
 
     - name: POSTGRESQL | Install postgres
       apt:
         pkg: "{{ item }}"
         state: latest
       with_items:
         - postgresql
         - postgresql-contrib
       register: postgresinstalled
       when: not postgres_exists.stat.exists
       
     - name: POSTGRES | Add postgres config
       when: postgresinstalled|success
       file: src=pg_hba.conf dest=/etc/postgresql/9.5/main owner=root group=root
